language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-gulp' ]; then cd .. && eval "mv $currentfolder generator-angular-gulp" && cd generator-angular-gulp; fi
